apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-be
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mehmetdolu/gitops-team-be.git
    path: guestbook
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: team-be

