apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-be
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mehmetdolu/gitops-team-be
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: team-be 

